### ISSUE TITLE
Missing files in gatsby-i18next node_modules folder

### ISSUE THREAD

**Issue by Pustelto** [hupe1980/gatsby-i18n#3]
Hi @hupe1980 , I want to use your plugin for one project I'm working on. But I'm unable to do so. When I type `npm start` I always get errors like this during startup: `Error: Cannot find module './lib/plugin'` and once localhost starts I get error:

```
These relative modules were not found:

* ./Head in ./node_modules/@wapps/gatsby-i18n/lib/index.js
* ./I18nContext in ./node_modules/@wapps/gatsby-i18n/lib/index.js
* ./Language in ./node_modules/@wapps/gatsby-i18n/lib/index.js
* ./Link in ./node_modules/@wapps/gatsby-i18n/lib/index.js
* ./Redirect in ./node_modules/@wapps/gatsby-i18n/lib/index.js
```

I have checked content of node_modules folder of gatsby-i18next and there files are indeed missing. Is there some bug in released package or I'm doing something wrong. I couldn't find any relevant info on this.

Thanks for help.

**Comment by hupe1980** [comment]
Hi @Pustelto... the bug is fixed

**Comment by Pustelto** [comment]
Oh, thanks for quick response. I will try it today.

**Comment by Pustelto** [comment]
It works fine now, thank you for help.

**Comment by Pustelto** [comment]
Hi @hupe1980, still getting one error: 
```
error Plugin @wapps/gatsby-plugin-i18next returned an error:
Error: Cannot find module '@wapps/gatsby-i18n/src/plugin/fragments.js'
```

Also, can I somehow config i18next options? Like keySeparator. I have paragraph to translate and periods after sentence are treated as key separators so the key is nested and translation do not work. I need to turn this of. 

Thanks

**Comment by hupe1980** [comment]
Hi @Pustelto... the bug is fixed and i added i18nextOptions as pluginOptions... 
Look at the starter if you need an example.

**Comment by Pustelto** [comment]
Hi, thanks for great support. Took me a little bit time to oriented in the plugin (but that was due to me going over several i18n solutions for gatsby) but the plugins is great and really easy to  use in the end. 👍
